### ISSUE TITLE
Select Options for Website Look from {Wrap} Bootstrap

### ISSUE THREAD

**Issue by Tryxie1** [patrickdenglerhobbisoft/TrivediEffect#8]
Kelly will select options in which to choose a website design from https://wrapbootstrap.com.

**Comment by Tryxie1** [comment]
I like the look and feel of the first one the best, but not sure if we can cut down the amount of scrolling for the first page?

http://wrapbootstrap.com/preview/WB0916093 

http://wrapbootstrap.com/preview/WB0K0225M

http://wrapbootstrap.com/preview/WB0T7G33N

http://wrapbootstrap.com/preview/WB00K28BD

**Comment by christopherdude** [comment]
I liked the third one, but I need someone to make a call here b4 I start, as this is a lot of work, converting these.  I don't want to go down one path and have it change.  I'm ASSUMING this is for the outward facing site.  If so, are we ignoring then whatever they've already chosen?  Or?  

Just assigning this back to Kelly to see if she can answer these questions.  Once you've answered, please re-assign me.  :)

**Comment by Tryxie1** [comment]
Ok, I was just looking at look and feel. That’s why I liked the first one. But, we have to wait to hear back from Alice/Chuck if we’re moving forward on this.

**Comment by christopherdude** [comment]
Yeah, I really need that answer..

**Comment by Tryxie1** [comment]
We've chosen: http://templateninja.net/themes/dodolanmanuk/v1.1/black/
